### ISSUE TITLE
Repository file structure

### ISSUE THREAD

**Issue by matdhart** [IUS-CS/3MasterGames#37]
**Issue**
The /src folder lacks any further file structure, such as additional directories. The file structure of the source folder should reflect on the design of the system, for instance any data files (.xml) should be stored separately from the actual source code. Also related source code files should be grouped together in a directory, for instance all UI components should be separate from XML parsing components.

**Benefits**
Much more clear grouping and separation of code
File hierarchy reflects the hierarchy of the code

**Comment by Cliftonz** [comment]
I have restructured our files, this well be reflected in our next update.
